image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - set -eo pipefail
  - bundle install

after_script:
  - set -eo pipefail
  - >-
        curl
        "https://api.cloudflare.com/client/v4/zones/9fb9447e3887048b5f9a23c9697bac46/purge_cache"
        -H "X-Auth-Email: ohad188@gmail.com"
        -H "X-Auth-Key: $CLOUDFLARE_API_KEY"
        -H "Content-Type: application/json"
        -X DELETE
        --data '
        {
        "purge_everything":true
        }
        '
        -v
  
test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - set -eo pipefail
  - apt-get update -y
  - apt-get install -y locales
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
